require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WorkshiftsController do

  # This should return the minimal set of attributes required to create a valid
  # Workshift. As you add validations to Workshift, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WorkshiftsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all workshifts as @workshifts" do
      workshift = Workshift.create! valid_attributes
      get :index, {}, valid_session
      assigns(:workshifts).should eq([workshift])
    end
  end

  describe "GET show" do
    it "assigns the requested workshift as @workshift" do
      workshift = Workshift.create! valid_attributes
      get :show, {:id => workshift.to_param}, valid_session
      assigns(:workshift).should eq(workshift)
    end
  end

  describe "GET new" do
    it "assigns a new workshift as @workshift" do
      get :new, {}, valid_session
      assigns(:workshift).should be_a_new(Workshift)
    end
  end

  describe "GET edit" do
    it "assigns the requested workshift as @workshift" do
      workshift = Workshift.create! valid_attributes
      get :edit, {:id => workshift.to_param}, valid_session
      assigns(:workshift).should eq(workshift)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Workshift" do
        expect {
          post :create, {:workshift => valid_attributes}, valid_session
        }.to change(Workshift, :count).by(1)
      end

      it "assigns a newly created workshift as @workshift" do
        post :create, {:workshift => valid_attributes}, valid_session
        assigns(:workshift).should be_a(Workshift)
        assigns(:workshift).should be_persisted
      end

      it "redirects to the created workshift" do
        post :create, {:workshift => valid_attributes}, valid_session
        response.should redirect_to(Workshift.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved workshift as @workshift" do
        # Trigger the behavior that occurs when invalid params are submitted
        Workshift.any_instance.stub(:save).and_return(false)
        post :create, {:workshift => {  }}, valid_session
        assigns(:workshift).should be_a_new(Workshift)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Workshift.any_instance.stub(:save).and_return(false)
        post :create, {:workshift => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested workshift" do
        workshift = Workshift.create! valid_attributes
        # Assuming there are no other workshifts in the database, this
        # specifies that the Workshift created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Workshift.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => workshift.to_param, :workshift => { "these" => "params" }}, valid_session
      end

      it "assigns the requested workshift as @workshift" do
        workshift = Workshift.create! valid_attributes
        put :update, {:id => workshift.to_param, :workshift => valid_attributes}, valid_session
        assigns(:workshift).should eq(workshift)
      end

      it "redirects to the workshift" do
        workshift = Workshift.create! valid_attributes
        put :update, {:id => workshift.to_param, :workshift => valid_attributes}, valid_session
        response.should redirect_to(workshift)
      end
    end

    describe "with invalid params" do
      it "assigns the workshift as @workshift" do
        workshift = Workshift.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Workshift.any_instance.stub(:save).and_return(false)
        put :update, {:id => workshift.to_param, :workshift => {  }}, valid_session
        assigns(:workshift).should eq(workshift)
      end

      it "re-renders the 'edit' template" do
        workshift = Workshift.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Workshift.any_instance.stub(:save).and_return(false)
        put :update, {:id => workshift.to_param, :workshift => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested workshift" do
      workshift = Workshift.create! valid_attributes
      expect {
        delete :destroy, {:id => workshift.to_param}, valid_session
      }.to change(Workshift, :count).by(-1)
    end

    it "redirects to the workshifts list" do
      workshift = Workshift.create! valid_attributes
      delete :destroy, {:id => workshift.to_param}, valid_session
      response.should redirect_to(workshifts_url)
    end
  end

end
